name: Deploy via FTP
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v2
      with:
        url: ${{ secrets.HOSPEDAGEM }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
        localDir: "site"
        remoteDir: "."
