name: Deploy via FTP
on:
  push:
    branches: 
      - api/site
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: ${{ secrets.HOSPEDAGEM }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
        syncroot: "./site/"
